# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: MV Design System
email: martin.svoboda@lundegaard.eu
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/mv-design-system" # the subpath of your site, e.g. /blog
url: "https://martinsvoboda.github.io/" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-remote-theme

# Setup pattern collection
collections:
  patterns:
    output: true


# Set theme
remote_theme: lundegaard/design-system-template  # you can specify git branch or commit lundegaard/design-system-template@v0.1.0

# Overriding default colors
branding:
  logo_path: '/assets/pvs-logo-mobile.svg'
  navigation_background_color: '#2362a2'
  navigation_link_color: '#fff'
  navigation_link_color_hover: '#ecae1a'
  main_background_color: '#f5f5f5'